/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-add-campaign': RouteRecordInfo<'admin-add-campaign', '/admin/AddCampaign', Record<never, never>, Record<never, never>>,
    'admin-admin-panel': RouteRecordInfo<'admin-admin-panel', '/admin/AdminPanel', Record<never, never>, Record<never, never>>,
    'admin-company-list': RouteRecordInfo<'admin-company-list', '/admin/CompanyList', Record<never, never>, Record<never, never>>,
    'admin-contract-manager': RouteRecordInfo<'admin-contract-manager', '/admin/ContractManager', Record<never, never>, Record<never, never>>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'admin-garage-manager': RouteRecordInfo<'admin-garage-manager', '/admin/GarageManager', Record<never, never>, Record<never, never>>,
    'admin-payment-manager': RouteRecordInfo<'admin-payment-manager', '/admin/PaymentManager', Record<never, never>, Record<never, never>>,
    'admin-user-manager': RouteRecordInfo<'admin-user-manager', '/admin/UserManager', Record<never, never>, Record<never, never>>,
    'admin-vehicle-manager': RouteRecordInfo<'admin-vehicle-manager', '/admin/VehicleManager', Record<never, never>, Record<never, never>>,
    'company-campaign-list': RouteRecordInfo<'company-campaign-list', '/company/CampaignList', Record<never, never>, Record<never, never>>,
    'company-campaign-vehicles': RouteRecordInfo<'company-campaign-vehicles', '/company/CampaignVehicles', Record<never, never>, Record<never, never>>,
    'company-company-dashboard': RouteRecordInfo<'company-company-dashboard', '/company/CompanyDashboard', Record<never, never>, Record<never, never>>,
    'company-company-profile': RouteRecordInfo<'company-company-profile', '/company/CompanyProfile', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'owner-contract-view': RouteRecordInfo<'owner-contract-view', '/owner/ContractView', Record<never, never>, Record<never, never>>,
    'owner-owner-dashboard': RouteRecordInfo<'owner-owner-dashboard', '/owner/OwnerDashboard', Record<never, never>, Record<never, never>>,
    'owner-payment-history': RouteRecordInfo<'owner-payment-history', '/owner/PaymentHistory', Record<never, never>, Record<never, never>>,
    'owner-profile': RouteRecordInfo<'owner-profile', '/owner/Profile', Record<never, never>, Record<never, never>>,
    'owner-register-vehicle': RouteRecordInfo<'owner-register-vehicle', '/owner/RegisterVehicle', Record<never, never>, Record<never, never>>,
    'owner-vehicle-status': RouteRecordInfo<'owner-vehicle-status', '/owner/VehicleStatus', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
