/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-AddCampaign': RouteRecordInfo<'admin-AddCampaign', '/admin/AddCampaign', Record<never, never>, Record<never, never>>,
    'admin-AdminPanel': RouteRecordInfo<'admin-AdminPanel', '/admin/AdminPanel', Record<never, never>, Record<never, never>>,
    'admin-CompanyList': RouteRecordInfo<'admin-CompanyList', '/admin/CompanyList', Record<never, never>, Record<never, never>>,
    'admin-ContractManager': RouteRecordInfo<'admin-ContractManager', '/admin/ContractManager', Record<never, never>, Record<never, never>>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'admin-GarageManager': RouteRecordInfo<'admin-GarageManager', '/admin/GarageManager', Record<never, never>, Record<never, never>>,
    'admin-PaymentManager': RouteRecordInfo<'admin-PaymentManager', '/admin/PaymentManager', Record<never, never>, Record<never, never>>,
    'admin-UserManager': RouteRecordInfo<'admin-UserManager', '/admin/UserManager', Record<never, never>, Record<never, never>>,
    'admin-VehicleManager': RouteRecordInfo<'admin-VehicleManager', '/admin/VehicleManager', Record<never, never>, Record<never, never>>,
    'company-CampaignList': RouteRecordInfo<'company-CampaignList', '/company/CampaignList', Record<never, never>, Record<never, never>>,
    'company-CampaignVehicles': RouteRecordInfo<'company-CampaignVehicles', '/company/CampaignVehicles', Record<never, never>, Record<never, never>>,
    'company-CompanyDashboard': RouteRecordInfo<'company-CompanyDashboard', '/company/CompanyDashboard', Record<never, never>, Record<never, never>>,
    'company-CompanyProfile': RouteRecordInfo<'company-CompanyProfile', '/company/CompanyProfile', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'owner-ContractView': RouteRecordInfo<'owner-ContractView', '/owner/ContractView', Record<never, never>, Record<never, never>>,
    'owner-OwnerDashboard': RouteRecordInfo<'owner-OwnerDashboard', '/owner/OwnerDashboard', Record<never, never>, Record<never, never>>,
    'owner-PaymentHistory': RouteRecordInfo<'owner-PaymentHistory', '/owner/PaymentHistory', Record<never, never>, Record<never, never>>,
    'owner-Profile': RouteRecordInfo<'owner-Profile', '/owner/Profile', Record<never, never>, Record<never, never>>,
    'owner-RegisterVehicle': RouteRecordInfo<'owner-RegisterVehicle', '/owner/RegisterVehicle', Record<never, never>, Record<never, never>>,
    'owner-VehicleStatus': RouteRecordInfo<'owner-VehicleStatus', '/owner/VehicleStatus', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
